apiVersion: v1
kind: Service
metadata:
  name: feedback-frontend-service
spec:
  selector:
    app: feedback-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
